name: Test and Start React App

on:
  push:
    branches:
      - '**'  # Run on ANY branch push
  pull_request:
    branches:
      - '**'  # Run on ANY pull request

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests

      - name: Build app
        run: npm run build

      - name: Start app and verify it's running
        run: |
          npm install -g wait-on  # install wait-on
          npm start &             # start app in background
          wait-on http://localhost:3000 --timeout 30000  # wait up to 30s
